language: generic 
sudo: required
services:
  - docker
 
before_install:
  # using the dev version because the prod version does not allow for testing
  - docker build -t "$DOCKER_ID"/multi-docker-fib -f ./client/Dockerfile.dev ./client

script:
  # - docker run "$DOCKER_ID"/multi-docker-fib npm run test -- --coverage
  - docker run -e CI=true fusion52/multi-docker-fib npm test

after_success:
  - docker build -t "$DOCKER_ID"/multi-docker-fib-client:latest ./client
  - docker build -t "$DOCKER_ID"/multi-docker-fib-nginx:latest ./nginx
  - docker build -t "$DOCKER_ID"/multi-docker-fib-server:latest ./server
  - docker build -t "$DOCKER_ID"/multi-docker-fib-worker:latest ./worker
  # Login into the Docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub.
  - docker push "$DOCKER_ID"/multi-docker-fib-client:latest
  - docker push "$DOCKER_ID"/multi-docker-fib-nginx:latest
  - docker push "$DOCKER_ID"/multi-docker-fib-server:latest
  - docker push "$DOCKER_ID"/multi-docker-fib-worker:latest

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker-fib'
  env: 'MultiDockerFib-env'
  bucket_name: 'elasticbeanstalk-us-east-1-559681517647'
  bucket_path: 'multi-docker-fib'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
