sudo: required
services:
  - docker

before_install:
  - docker build -t fusion52/multi-docker-fib -f ./client/Dockerfile.dev ./client

script:
  - docker run fusion52/multi-docker-fib npm run test -- --coverage

after_success:
  - docker build -t fusion52/multi-docker-fib-client ./client
  - docker build -t fusion52/multi-docker-fib-nginx ./nginx
  - docker build -t fusion52/multi-docker-fib-server ./server
  - docker build -t fusion52/multi-docker-fib-worker ./worker
  # Login into the Docker CLI
  - docker -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take those images and push them to Docker Hub
  - docker push fusion52/multi-docker-fib-client
  - docker push fusion52/multi-docker-fib-nginx
  - docker push fusion52/multi-docker-fib-server
  - docker push fusion52/multi-docker-fib-worker
